### ISSUE TITLE
New feature: Add weight attribute

### ISSUE THREAD

**Issue by tomschelsen** [green-spaces/enum-derived#11]
Hi,

Do you think it would be possible to add a simple (user-wise) weight attribute as in https://github.com/alvra/generate-random#example ?

Thanks a lot

**Comment by green-spaces** [comment]
Hello!

I'm pretty sure this wont be an issue to add. Its a nice extension of the current API! Thank you for the suggestion!

If you can answer some questions about your use that would be awesome!

1) Is there some thing you need from my crate that Generate-Random doesn't do? 

2) Can you tell me about how you're using this crate?

3)  How did you find this crate?

Thanks!

**Comment by green-spaces** [comment]
Added an implementation of the feature and released it in the 0.6.0 version.

**Comment by tomschelsen** [comment]
Wow, that was fast, thanks :)

To answer your questions nonetheless:

1. The main seller was #[custom_rand()] that allows to just define a function instead of having to impl some of rand's traits. From what I have seen Generate-Random doesn't offers this feature
2. The program I am writing generates textual messages that are later used to train a Natural Language Understanding model. So the aim is diversity, but the information those messages convey are quite structured and the values must not be completely random (we are in aeronautics territory, so having a temperature or wind value that could never happen in reality doesn't make much sense). All that to say that I've got lots of custom types (either enums when it makes sense, or tuple structs when holding numerical values) that are not in std for which I need to implement a random generator for, aggregate all that in a "state" struct (and then call the already implemented state -> natural language message translation function).
3. I searched on crates.io for rand + enum/struct + derive. Quite a few results, to be honest it's a bit tricky to find the one that does it all (recursive derive for enum and structs, with already implemented generators for std types + possibility to add custom functions without much boilerplate) or to know which are in active development or not, but hey, already happy with what I found :)

**Comment by green-spaces** [comment]
Thanks for taking the time to let me know how you're using it! 

I've been updated the crate description to reflect it's current functionality and it now ranks much better on crates.io for the combination of  'enum' + 'rand'/'random'. The documentation is now updated to highlight the custom_rand and weight attributes too.

Being able to recursively derive `Rand` would be a great feature to add. This will be the next one I work on! 

Thank you for all the feedback and sharing how you're using this project!

**Comment by green-spaces** [comment]
Nested derives are now supported in version 0.7.0.
